this.BTD_mustaches = this.BTD_mustaches||{};
this.BTD_mustaches = {
	  space_container :
			 '<div class="spaces-container">'
			+'  <ul class="spaces">'
			+'		<li class="space-item">'
			+'			<a class="btn-show-all btn btn-alt js-spaces-action" data-action="show-all" href="#">'
			+'				<span class="space-counter"></span>'
			+'				<div class="content">All</div>'
			+'			</a>'
			+'			{{#spaces}}'
			+'				<li class="space-item">'
			+'					<div class="button-group">'
			+'						<a class="btn-show-space btn btn-alt js-spaces-action" data-action="show-space" data-space="{{id}}" href="javascript:void(0)">'
			+'							<span class="space-counter"></span>'
			+'							<div class="content">{{name}}</div>'
			+'						</a>'
			+'						<a class="btn-edit-space btn btn-alt btn-primary js-spaces-action" data-action="edit-space" data-space="{{id}}" href="javascript:void(0)"> <i class="icon icon-settings"></i> <span class="is-vishidden">Settings</span> </span></a>'
			+'					</div>'
			+'				</li>'
			+'			{{/spaces}}'
			+'		</li>'
			+'		<li class="add-space-item">'
			+'			<a class="btn btn-alt js-spaces-action" data-action="add-space" href="javascript:void(0)">'
			+'				<div class="content"></div>'
			+'			</a>'
			+'		</li>'
			+'	</ul>'
			+'</div>'
	, spaces_dialog : 
			 '<form action="#" id="list_details" accept-charset="utf-8" class="frm s-fullform"><section><fieldset>'
			+'	<div class="control-group">'
			+'		<label for="list-name" class="control-label">Name</label>'
			+'		<div class="controls">'
			+'			<input class="xlarge" id="space-name" name="space-name" maxlength="25" required="required" type="text">'
			+'		</div>'
			+'	</div>'
			+'	<div>'
			+'		<label for="space-ids" class="control-label">Columns</label>'
			+'		<div class="space-list-container">'
			+'			<ul class="control-group">'
			+'			{{#columns}}'
			+'				<li>'
			+'					<label class="checkbox">'
			+'						<input type="checkbox" name="space-ids" value="{{key}}"/>'
			+'							<span>{{title}}</span>'
			+'					</label>'
			+'				</li>'
			+'			{{/columns}}'
			+'			</ul>'
			+'		</div>'
			+'	</div>'
			+'</fieldeset></section></form>'
	, spaces_dialog_footer : 
			 '<button class="js-remove-space btn btn-back btn-delete" style="">Remove space</button>'
			+'<span class="fr"><button class="js-add-space btn btn-primary" style="display: inline-block;"><i class="add"></i>Add space</button> </span>'
}
